/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    DynamicButton: typeof import('./src/components/DynamicButton.vue')['default']
    EnvChecker: typeof import('./src/components/EnvChecker.vue')['default']
    FileUploader: typeof import('./src/components/FileUploader.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
  }
}
